version: "3"

services:
  authorization-web-api:
    build:
      context: .
      dockerfile: ./Dockerfile-authorization
    ports:
      - "9000:8000"
    expose:
      - "9000"
    env_file:
     - ./api.env
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      
  management-web-api:
    build:
      context: .
      dockerfile: ./Dockerfile-management
    volumes:
      - /root/Files:/root/Files
    ports:
      - "9001:8001"
    expose:
      - "9001"
    env_file:
     - ./api.env
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
  
  payments-web-api:
    build:
      context: .
      dockerfile: ./Dockerfile-payments
    ports:
      - "9002:8002"
    expose:
      - "9002"
    env_file:
     - ./api.env
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
