FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /source

COPY Tests.Payment.WebApi/*.csproj Tests.Payment.WebApi/
COPY Tests.Dal/*.csproj Tests.Dal/
COPY Tests.Bll/*.csproj Tests.Bll/
COPY Tests.Security/*.csproj Tests.Security/
COPY Tests.Utilities/*.csproj Tests.Utilities/
COPY Tests.Bll.Template/*.csproj Tests.Bll.Template/

RUN dotnet restore Tests.Payment.WebApi/Tests.Payment.WebApi.csproj

COPY Tests.Payment.WebApi/ Tests.Payment.WebApi/
COPY Tests.Dal/ Tests.Dal/
COPY Tests.Bll/ Tests.Bll/
COPY Tests.Security/ Tests.Security/
COPY Tests.Utilities/ Tests.Utilities/
COPY Tests.Bll.Template/ Tests.Bll.Template/
WORKDIR /source/Tests.Payment.WebApi
RUN dotnet build -c release

FROM build AS publish
RUN dotnet publish -c release --no-build -o /app

FROM mcr.microsoft.com/dotnet/aspnet:3.1
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Tests.Payment.WebApi.dll"]