version: "3"

services:
  authorization-web-api:
    build:
      context: .
      dockerfile: ./Dockerfile-authorization
    ports:
      - "${AUTHORIZATION_API_PORT_DEV}:8000"
    expose:
      - "${AUTHORIZATION_API_PORT_DEV}"
    env_file:
     - ./.env
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      
  management-web-api:
    build:
      context: .
      dockerfile: ./Dockerfile-management
    volumes:
      - /root/Files:/root/Files
    ports:
      - "${MANAGEMENT_API_PORT_DEV}:8001"
    expose:
      - "${MANAGEMENT_API_PORT_DEV}"
    env_file:
     - ./.env
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
  
  payments-web-api:
    build:
      context: .
      dockerfile: ./Dockerfile-payments
    ports:
      - "${PAYMENTS_API_PORT_DEV}:8002"
    expose:
      - "${PAYMENTS_API_PORT_DEV}"
    env_file:
     - ./.env
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
