name: Deploy API

env:
  directoryName: 'Tests_dev'

on:
  push:
    branches: 
      - 'development/**'
    

jobs:
  update-source:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout on host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: rm -rf ${{env.directoryName}} && git clone https://github.com/${{github.repository}} ${{env.directoryName}} && cd ${{env.directoryName}} && git fetch --all && git reset --hard origin/${{ steps.extract_branch.outputs.branch }} && git checkout ${{ steps.extract_branch.outputs.branch }}
  
  pass-envfile:
    needs: update-source
    runs-on: ubuntu-18.04

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASECONNECTIONSTRING: ${{ secrets.DATABASECONNECTIONSTRING }}
          envkey_MANAGEMENT_API_PORT_DEV: ${{ secrets.MANAGEMENT_API_PORT_DEV }}
          envkey_PAYMENTS_API_PORT_DEV: ${{ secrets.PAYMENTS_API_PORT_DEV }}
          envkey_AUTHORIZATION_API_PORT_DEV: ${{ secrets.AUTHORIZATION_API_PORT_DEV }}
          file_name: .env

      - name: Move envfile to host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ".env"
          target: "${{env.directoryName}}/"
  
  deploy:
    needs: pass-envfile
    runs-on: ubuntu-18.04

    steps:
      - name: Docker compose restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd ${{env.directoryName}} && docker-compose down && docker-compose up --build --detach
  