name: Deploy Tests.Authorization.WebApi

on:
  push:
    branches: [docker-deploy]
    

jobs:
  pass-envfile:
    runs-on: ubuntu-18.04

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_DATABASECONNECTIONSTRING: ${{ secrets.SECRET_KEY }}
          file_name: api.env

      - name: Move envfile to host
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            source: "api.env"
            target: "/root/"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0

      - name: List builded files
        run: ls
