name: Deploy API

on:
  push:
    branches: [docker-deploy]
    

jobs:
  pass-envfile:
    runs-on: ubuntu-18.04

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_DATABASECONNECTIONSTRING: ${{ secrets.DATABASECONNECTIONSTRING }}
          file_name: development_api.env

      - name: Move envfile to host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "development_api.env"
          target: "/root/"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout on host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: rm -rf Tests && git clone https://github.com/OneZeroZeroOneOne/Tests Tests && cd Tests && git fetch --all && git reset --hard origin/${{ steps.extract_branch.outputs.branch }} && git checkout ${{ steps.extract_branch.outputs.branch }}