name: Deploy API

on:
  push:
    branches: 
      - 'development/**'
    

jobs:
  update-source:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout on host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: rm -rf Tests_dev && git clone https://github.com/OneZeroZeroOneOne/Tests Tests_dev && cd Tests_dev && git fetch --all && git reset --hard origin/${{ steps.extract_branch.outputs.branch }} && git checkout ${{ steps.extract_branch.outputs.branch }}
  
  pass-envfile:
    needs: update-source
    runs-on: ubuntu-18.04

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_DATABASECONNECTIONSTRING: ${{ secrets.DATABASECONNECTIONSTRING }}
          file_name: api.env

      - name: Move envfile to host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "api.env"
          target: "Tests_dev/"
  
  deploy:
    needs: pass-envfile
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout on host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd Tests_dev && docker-compose down && docker-compose up --build --detach
  